### ISSUE TITLE
Boxed error when ./seed bloop

### ISSUE THREAD

**Issue by PhilAndrew** [tindzk/seed#82]
Boxed error when ./seed bloop

```
Exception in thread "main" java.util.concurrent.ExecutionException: Boxed Error
	at scala.concurrent.impl.Promise$.resolver(Promise.scala:87)
	at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:79)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:284)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: assertion failed: Attempts to download https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.6.7.3/jackson-databind-2.6.7.3-sources.jar twice in parallel
	at scala.Predef$.assert(Predef.scala:223)
	at coursier.cache.loggers.RefreshLogger$UpdateDisplayRunnable.newEntry(RefreshLogger.scala:82)
	at coursier.cache.loggers.RefreshLogger.downloadingArtifact(RefreshLogger.scala:227)
	at coursier.cache.FileCache.$anonfun$download$25(FileCache.scala:422)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	... 5 more
```

**Comment by tindzk** [comment]
Can you reproduce it reliably? I have largely rewritten this part of the code in #77, so the bug might be fixed once the pull request has been merged.

**Comment by PhilAndrew** [comment]
No.
