### ISSUE TITLE
Cannot import java bom file

### ISSUE THREAD

**Issue by PhilAndrew** [tindzk/seed#84]
https://search.maven.org/artifact/software.amazon.awssdk/bom/2.10.65/pom

```
[module.ideal.jvm]
root = "jvm"
sources = ["jvm/src"]
scalaDeps = [["com.github.seratch", "awscala", "0.8.+"],
              ["org.wvlet.airframe", "airframe", "20.2.1"]]
javaDeps = [["software.amazon.awssdk", "pom", "2.10.65"]]
```

Gives error for `javaDeps = [["software.amazon.awssdk", "pom", "2.10.65"]]`

```
Exception in thread "main" coursier.error.ResolutionError$CantDownloadModule: Error downloading software.amazon.awssdk:pom:2.10.65
  not found: /Users/philip/.ivy2/local/software.amazon.awssdk/pom/2.10.65/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/software/amazon/awssdk/pom/2.10.65/pom-2.10.65.pom
	at coursier.Resolve$.$anonfun$validate$1(Resolve.scala:359)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at coursier.Resolve$.validate(Resolve.scala:357)
	at coursier.Resolve.validate0$1(Resolve.scala:139)
	at coursier.Resolve.$anonfun$ioWithConflicts0$4(Resolve.scala:183)
	at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:11)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by tindzk** [comment]
There is a typo. The correct name should be `bom` instead of `pom`.

**Comment by PhilAndrew** [comment]
If bom then the error is 

```
➜  ideal git:(master) ✗ ./seed bloop
ⓘ Loading project build.toml...
ⓘ Configured resolvers:
  - /Users/philip/.ivy2/local (Ivy)
  - /Users/philip/Library/Caches/Coursier/v1 (Coursier)
  - https://repo1.maven.org/maven2 (Maven)
ⓘ Resolving platform artefacts...
↪ Resolving 17 dependencies from com.github.seratch, dev.zio, io.monix, org.scala-js, org.scala-native, org.wvlet.airframe, software.amazon.awssdk...
Exception in thread "main" coursier.error.ResolutionError$Several: Error downloading com.fasterxml.jackson.core:jackson-annotations:
  not found: /Users/philip/.ivy2/local/com.fasterxml.jackson.core/jackson-annotations/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations//jackson-annotations-.pom
Error downloading com.fasterxml.jackson.core:jackson-databind:
  not found: /Users/philip/.ivy2/local/com.fasterxml.jackson.core/jackson-databind/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind//jackson-databind-.pom
Error downloading org.apache.httpcomponents:httpcore:
  not found: /Users/philip/.ivy2/local/org.apache.httpcomponents/httpcore/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore//httpcore-.pom
Error downloading software.amazon.eventstream:eventstream:
  not found: /Users/philip/.ivy2/local/software.amazon.eventstream/eventstream/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/software/amazon/eventstream/eventstream//eventstream-.pom
Error downloading org.apache.httpcomponents:httpclient:
  not found: /Users/philip/.ivy2/local/org.apache.httpcomponents/httpclient/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient//httpclient-.pom
Error downloading com.fasterxml.jackson.core:jackson-core:
  not found: /Users/philip/.ivy2/local/com.fasterxml.jackson.core/jackson-core/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core//jackson-core-.pom
Error downloading org.slf4j:slf4j-api:
  not found: /Users/philip/.ivy2/local/org.slf4j/slf4j-api/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/org/slf4j/slf4j-api//slf4j-api-.pom
	at coursier.error.ResolutionError$.from(ResolutionError.scala:70)
	at coursier.Resolve.validate0$1(Resolve.scala:141)
	at coursier.Resolve.$anonfun$ioWithConflicts0$4(Resolve.scala:183)
	at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:11)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
➜  ideal git:(master) ✗
```

**Comment by tindzk** [comment]
`bom` is not a regular artefact. It only contains a [Maven POM file](https://repo1.maven.org/maven2/software/amazon/awssdk/bom/2.10.65/). Such dependencies are not supported by sbt either. The best would be to include only those AWS dependencies for the services you use as per the [documentation](https://github.com/aws/aws-sdk-java-v2#individual-services).

**Comment by PhilAndrew** [comment]
Ok thanks !
